[package]
name = "advgame"
version = "0.1.0"
authors = ["Jacek Olczyk <jacek.olczyk98@gmail.com>"]

[dependencies]
ncurses = "5.97.0"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
lazy_static = "1.2.0"